# LIMPIEZA DE DATOS — POBLACIÓN ACTIVA (EPA)
### Encuesta de Población Activa: población de 16+ años por relación con la actividad, sexo y edad, 1976–2026
### Incluye:
- Importación de librerías
- Carga de datasets
- Conversión de tipos y limpieza
- Unión de series y homogenización metodológica
- Exportación de archivos finales

---
**Fuentes (INE, Encuesta de Población Activa):**
- `76_95 Población de 16 y más años por sexo, grupos de edad (4) y relación con la actividad económica.csv`, *Población por sexo, edad y relación con la actividad.* Cobertura: 1976T3–1995T4. Trimestral.
- `96_01 Población de 16 y más años por sexo, grupos de edad (4), relación con la actividad económica y Periodo.csv`, *Población por sexo, edad y relación con la actividad.* Cobertura: 1996T1–2001T4. Trimestral.
- `Población de 16 y más años por relación con la actividad económica, sexo y grupo de edad.csv`, *Población por relación con la actividad, sexo y edad.* Cobertura: 2002T1–2026T1. Trimestral.

# 0. Importación de "Librerías"

In [39]:
import pandas as pd
import plotly.express as px

# 1. Carga de datasets

In [40]:
ruta = '../Fuentes/INE/EPA/1. Población en viviendas familiares/'

### Serie de 1976 a 1995

In [41]:
df_76_95 = pd.read_csv(ruta + '76_95/'+ '76_95 Población de 16 y más años por sexo, grupos de edad (4) y relación con la actividad económica.csv', sep=';', encoding='utf-8-sig')
df_76_95

,Sexo,Grupos de edad (4),Relación con la actividad económica,Periodo,Total
0,Ambos sexos,Total,Población de 16 y más años,1995TIV,"31.956,3"
1,Ambos sexos,Total,Población de 16 y más años,1995TIII,"31.883,6"
2,Ambos sexos,Total,Población de 16 y más años,1995TII,"31.810,9"
3,Ambos sexos,Total,Población de 16 y más años,1995TI,"31.738,2"
4,Ambos sexos,Total,Población de 16 y más años,1994TIV,"31.665,5"
...,...,...,...,...,...
7015,Mujeres,De 55 y más años,Inactivos,1977TIII,"3.560,2"
7016,Mujeres,De 55 y más años,Inactivos,1977TII,"3.549,2"
7017,Mujeres,De 55 y más años,Inactivos,1977TI,"3.509,5"
7018,Mujeres,De 55 y más años,Inactivos,1976TIV,"3.472,3"
7019,Mujeres,De 55 y más años,Inactivos,1976TIII,"3.438,7"

In [42]:
df_76_95.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7020 entries, 0 to 7019
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 7020 non-null   object
 1   Grupos de edad (4)                   7020 non-null   object
 2   Relación con la actividad económica  7020 non-null   object
 3   Periodo                              7020 non-null   object
 4   Total                                7020 non-null   object
dtypes: object(5)
memory usage: 274.3+ KB

In [43]:
#Chequeoo para ver si usa la metodología antigua o la actual
df_filtrado = df_76_95.loc[(df_76_95['Relación con la actividad económica'] == 'Parados') &
                           (df_76_95['Sexo'] == 'Ambos sexos') &
                           (df_76_95['Periodo'].str.startswith('197') &
                            (df_76_95['Grupos de edad (4)'] == 'Total')
                            )]
df_filtrado[['Periodo', 'Total']].sort_values(by='Periodo').style.hide()

### Serie de 1996 a 2001

In [44]:
df_96_01 = pd.read_csv(ruta + '96_01/'+ '96_01 Población de 16 y más años por sexo, grupos de edad (4), relación con la actividad económica y Periodo.csv', sep=';', encoding='utf-8-sig')
df_96_01

,Sexo,Grupos de edad (4),Relación con la actividad económica,Periodo,Total
0,Ambos sexos,Total,Población de 16 y más años,2001TIV,"34.246,3"
1,Ambos sexos,Total,Población de 16 y más años,2001TIII,"34.126,9"
2,Ambos sexos,Total,Población de 16 y más años,2001TII,"34.007,4"
3,Ambos sexos,Total,Población de 16 y más años,2001TI,"33.888,0"
4,Ambos sexos,Total,Población de 16 y más años,2000TIV,"33.769,5"
...,...,...,...,...,...
2155,Mujeres,De 55 y más años,Inactivos,1997TI,"5.164,9"
2156,Mujeres,De 55 y más años,Inactivos,1996TIV,"5.148,2"
2157,Mujeres,De 55 y más años,Inactivos,1996TIII,"5.126,9"
2158,Mujeres,De 55 y más años,Inactivos,1996TII,"5.106,3"
2159,Mujeres,De 55 y más años,Inactivos,1996TI,"5.094,9"

In [45]:
df_96_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 2160 non-null   object
 1   Grupos de edad (4)                   2160 non-null   object
 2   Relación con la actividad económica  2160 non-null   object
 3   Periodo                              2160 non-null   object
 4   Total                                2160 non-null   object
dtypes: object(5)
memory usage: 84.5+ KB

In [46]:
#Chequeoo para ver si usa la metodología antigua o la actual
df_filtrado = df_96_01.loc[(df_96_01['Relación con la actividad económica'] == 'Parados') &
                           (df_96_01['Sexo'] == 'Ambos sexos') &
                           (df_96_01['Periodo'].str.startswith('199') &
                            (df_96_01['Grupos de edad (4)'] == 'Total')
                            )]
df_filtrado[['Periodo', 'Total']].sort_values(by='Periodo').style.hide()

### Serie de 2002 a 2025

In [47]:
df_02_25 = pd.read_csv(ruta + 'Población de 16 y más años por relación con la actividad económica, sexo y grupo de edad.csv', sep=';', encoding='latin1')
df_02_25

,Sexo,Edad,Relación con la actividad económica,Periodo,Total
0,Ambos sexos,Total,Total,2025T4,"42.315,3"
1,Ambos sexos,Total,Total,2025T3,"42.161,5"
2,Ambos sexos,Total,Total,2025T2,"42.048,5"
3,Ambos sexos,Total,Total,2025T1,"41.921,3"
4,Ambos sexos,Total,Total,2024T4,"41.810,1"
...,...,...,...,...,...
22459,Mujeres,70 y más años,Inactivos,2003T1,"2.895,9"
22460,Mujeres,70 y más años,Inactivos,2002T4,"2.889,8"
22461,Mujeres,70 y más años,Inactivos,2002T3,"2.875,1"
22462,Mujeres,70 y más años,Inactivos,2002T2,"2.855,4"
22463,Mujeres,70 y más años,Inactivos,2002T1,"2.814,1"

In [48]:
df_02_25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22464 entries, 0 to 22463
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 22464 non-null  object
 1   Edad                                 22464 non-null  object
 2   Relación con la actividad económica  22464 non-null  object
 3   Periodo                              22464 non-null  object
 4   Total                                22464 non-null  object
dtypes: object(5)
memory usage: 877.6+ KB

In [49]:
#Chequeoo para ver si usa la metodología antigua o la actual
df_filtrado = df_02_25.loc[(df_02_25['Relación con la actividad económica'] == 'Parados') &
                           (df_02_25['Sexo'] == 'Ambos sexos') &
                           (df_02_25['Periodo'].str.startswith('200') &
                            (df_02_25['Edad'] == 'Total')
                            )]
df_filtrado[['Periodo', 'Total']].sort_values(by='Periodo').style.hide()

### Chequeo en conjunto

In [50]:
dataframes = [df_76_95, df_96_01, df_02_25]

df_76_95.attrs['nombre'] = 'df_76_95'
df_96_01.attrs['nombre'] = 'df_96_01'
df_02_25.attrs['nombre'] = 'df_02_25'

In [51]:
# Valores únicos de cada dataset para ver las categorías
for df in dataframes:
    print(f'Valores únicos en {df.attrs['nombre']}')
    for columna in df:
        print(df[columna].unique())

Valores únicos en df_76_95
['Ambos sexos' 'Varones' 'Mujeres']
['Total' 'De 16 a 19 años' 'De 20 a 24 años' 'De 25 a 54 años'
 'De 55 y más años']
['Población de 16 y más años' 'Activos' 'Ocupados' 'Parados'
 'Parados que buscan primer empleo' 'Inactivos']
['1995TIV' '1995TIII' '1995TII' '1995TI' '1994TIV' '1994TIII' '1994TII'
 '1994TI' '1993TIV' '1993TIII' '1993TII' '1993TI' '1992TIV' '1992TIII'
 '1992TII' '1992TI' '1991TIV' '1991TIII' '1991TII' '1991TI' '1990TIV'
 '1990TIII' '1990TII' '1990TI' '1989TIV' '1989TIII' '1989TII' '1989TI'
 '1988TIV' '1988TIII' '1988TII' '1988TI' '1987TIV' '1987TIII' '1987TII'
 '1987TI' '1986TIV' '1986TIII' '1986TII' '1986TI' '1985TIV' '1985TIII'
 '1985TII' '1985TI' '1984TIV' '1984TIII' '1984TII' '1984TI' '1983TIV'
 '1983TIII' '1983TII' '1983TI' '1982TIV' '1982TIII' '1982TII' '1982TI'
 '1981TIV' '1981TIII' '1981TII' '1981TI' '1980TIV' '1980TIII' '1980TII'
 '1980TI' '1979TIV' '1979TIII' '1979TII' '1979TI' '1978TIV' '1978TIII'
 '1978TII' '1978TI' '1977TIV' '1977TIII' '1977TII' '1977TI' '1976TIV'
 '1976TIII']
['31.956,3' '31.883,6' '31.810,9' ... '3.509,5' '3.472,3' '3.438,7']
Valores únicos en df_96_01
['Ambos sexos' 'Varones' 'Mujeres']
['Total' 'De 16 a 19 años' 'De 20 a 24 años' 'De 25 a 54 años'
 'De 55 y más años']
['Población de 16 y más años' 'Activos' 'Ocupados' 'Parados'
 'Parados que buscan primer empleo' 'Inactivos']
['2001TIV' '2001TIII' '2001TII' '2001TI' '2000TIV' '2000TIII' '2000TII'
 '2000TI' '1999TIV' '1999TIII' '1999TII' '1999TI' '1998TIV' '1998TIII'
 '1998TII' '1998TI' '1997TIV' '1997TIII' '1997TII' '1997TI' '1996TIV'
 '1996TIII' '1996TII' '1996TI']
['34.246,3' '34.126,9' '34.007,4' ... '5.126,9' '5.106,3' '5.094,9']
Valores únicos en df_02_25
['Ambos sexos' 'Hombres' 'Mujeres']
['Total' 'De 16 a 19 años' 'De 20 a 24 años' 'De 25 a 29 años'
 'De 30 a 34 años' 'De 35 a 39 años' 'De 40 a 44 años' 'De 45 a 49 años'
 'De 50 a 54 años' 'De 55 a 59 años' 'De 60 a 64 años' 'De 65 a 69 años'
 '70 y más años']
['Total' 'Activos' 'Ocupados' 'Parados' 'Parados que buscan primer empleo'
 'Inactivos']
['2025T4' '2025T3' '2025T2' '2025T1' '2024T4' '2024T3' '2024T2' '2024T1'
 '2023T4' '2023T3' '2023T2' '2023T1' '2022T4' '2022T3' '2022T2' '2022T1'
 '2021T4' '2021T3' '2021T2' '2021T1' '2020T4' '2020T3' '2020T2' '2020T1'
 '2019T4' '2019T3' '2019T2' '2019T1' '2018T4' '2018T3' '2018T2' '2018T1'
 '2017T4' '2017T3' '2017T2' '2017T1' '2016T4' '2016T3' '2016T2' '2016T1'
 '2015T4' '2015T3' '2015T2' '2015T1' '2014T4' '2014T3' '2014T2' '2014T1'
 '2013T4' '2013T3' '2013T2' '2013T1' '2012T4' '2012T3' '2012T2' '2012T1'
 '2011T4' '2011T3' '2011T2' '2011T1' '2010T4' '2010T3' '2010T2' '2010T1'
 '2009T4' '2009T3' '2009T2' '2009T1' '2008T4' '2008T3' '2008T2' '2008T1'
 '2007T4' '2007T3' '2007T2' '2007T1' '2006T4' '2006T3' '2006T2' '2006T1'
 '2005T4' '2005T3' '2005T2' '2005T1' '2004T4' '2004T3' '2004T2' '2004T1'
 '2003T4' '2003T3' '2003T2' '2003T1' '2002T4' '2002T3' '2002T2' '2002T1']
['42.315,3' '42.161,5' '42.048,5' ... '2.875,1' '2.855,4' '2.814,1']

In [52]:
# Información acerca del tipo de dato y valores nulos de las columnas de cada dataset
for df in dataframes:
    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

Información acerca de df_76_95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7020 entries, 0 to 7019
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 7020 non-null   object
 1   Grupos de edad (4)                   7020 non-null   object
 2   Relación con la actividad económica  7020 non-null   object
 3   Periodo                              7020 non-null   object
 4   Total                                7020 non-null   object
dtypes: object(5)
memory usage: 274.3+ KB
None
Información acerca de df_96_01
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 2160 non-null   object
 1   Grupos de edad (4)                   2160 non-null   object
 2   Relación con la actividad económica  2160 non-null   object
 3   Periodo                              2160 non-null   object
 4   Total                                2160 non-null   object
dtypes: object(5)
memory usage: 84.5+ KB
None
Información acerca de df_02_25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22464 entries, 0 to 22463
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 22464 non-null  object
 1   Edad                                 22464 non-null  object
 2   Relación con la actividad económica  22464 non-null  object
 3   Periodo                              22464 non-null  object
 4   Total                                22464 non-null  object
dtypes: object(5)
memory usage: 877.6+ KB
None

# 2. Limpieza

### Transformación del tipo de dato y limpieza inicial

In [53]:
# Conversión de las variables categóricas a "category" por eficiencia
variables_categoricas = ['Sexo', 'Grupos de edad (4)', 'Edad','Relación con la actividad económica']

for i, df in enumerate(dataframes):
    for variable in variables_categoricas:
        if variable in df.columns:
            df[variable] = df[variable].astype('category')
        else:
            continue
    dataframes[i] = df

### Conversión de los datos numéricos a formato internacional, eliminar puntos y reemplazar las comas "," por puntos "."

In [54]:
for i in range(len(dataframes)):
    df = dataframes[i]

    # Convirtiendo a texto para poder manipularlo
    valores_limpios = df['Total'].astype(str).str.strip()

    # Eliminando los espacios internos y espacios irrompibles (\xa0) que usa el INE
    valores_limpios = valores_limpios.str.replace(' ', '', regex=False)
    valores_limpios = valores_limpios.str.replace('\xa0', '', regex=False)

    # Eliminando el punto de miles y cambiando la coma por punto
    valores_limpios = valores_limpios.str.replace('.', '', regex=False).str.replace(',', '.', regex=False)

    # Convirtiendo a numérico a numérico
    df['Total'] = pd.to_numeric(valores_limpios, errors='coerce')

    # Rellenando los nulos con 0.0 (valores que el INE guardaba con '..'
    df['Total'] = df['Total'].fillna(0.0)

    # Actualizamos la lista
    dataframes[i] = df

# Desempaquetamos fuera del bucle para no perder las referencias
df_76_95, df_96_01, df_02_25 = dataframes

In [55]:
# Información acerca del tipo de dato y valores nulos de las columnas de cada dataset
for df in dataframes:
    print()
    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

Información acerca de df_76_95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7020 entries, 0 to 7019
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 7020 non-null   category
 1   Grupos de edad (4)                   7020 non-null   category
 2   Relación con la actividad económica  7020 non-null   category
 3   Periodo                              7020 non-null   object
 4   Total                                7020 non-null   float64
dtypes: category(3), float64(1), object(1)
memory usage: 130.9+ KB
None

Información acerca de df_96_01
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 2160 non-null   category
 1   Grupos de edad (4)                   2160 non-null   category
 2   Relación con la actividad económica  2160 non-null   category
 3   Periodo                              2160 non-null   object
 4   Total                                2160 non-null   float64
dtypes: category(3), float64(1), object(1)
memory usage: 40.8+ KB
None

Información acerca de df_02_25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22464 entries, 0 to 22463
Data columns (total 5 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Sexo                                 22464 non-null  category
 1   Edad                                 22464 non-null  category
 2   Relación con la actividad económica  22464 non-null  category
 3   Periodo                              22464 non-null  object
 4   Total                                22464 non-null  float64
dtypes: category(3), float64(1), object(1)
memory usage: 417.9+ KB
None

### Transformación de los rangos de edad en las series temporales más recientes (2002 - 2025) para hgomogeneizar el dataset

In [56]:
categorias_a_unificar = [
    'De 55 a 59 años',
    'De 60 a 64 años',
    'De 65 a 69 años',
    '70 y más años'
]

df_02_25['Edad'] = df_02_25['Edad'].astype(str).str.strip()

columnas_agrupacion = ['Sexo', 'Relación con la actividad económica', 'Periodo']
for col in columnas_agrupacion:
    df_02_25[col] = df_02_25[col].astype(str)

# Creando la máscara para filtrar
mask = df_02_25['Edad'].isin(categorias_a_unificar)

# Agrupando los datos filtrados y sumamos el 'Total'
df = df_02_25[mask].groupby(columnas_agrupacion, as_index=False, observed=True)['Total'].sum(min_count=0)

# Creando la columna 'edad' con el nombre unificado
df['Edad'] = 'De 55 y más años'

# Eliminando las categorías no agrupadas
df_02_25 = df_02_25[~mask]

# Unimos la nueva categoría al dataset original del que provenían los datos
df_02_25 = pd.concat([df_02_25, df], ignore_index=True)

df_02_25['Edad'] = df_02_25['Edad'].astype('category')

for col in columnas_agrupacion:
    df_02_25[col] = df_02_25[col].astype('category')

dataframes[2] = df_02_25

### Transformación para homogeneizar con la única serie retropolada del INE (parados)

In [57]:
categorias_mas_25 = [
    'de 25 a 29 años',
    'de 30 a 34 años',
    'de 35 a 39 años',
    'de 40 a 44 años',
    'de 45 a 49 años',
    'de 50 a 54 años',
    'de 55 y más años',
    'de 25 a 54 años'
]


categorias_menos_25 = [
    'de 16 a 19 años',
    'de 20 a 24 años'
]
columnas_edad = ['Grupos de edad (4)', 'Edad']
for i, df in enumerate(dataframes):
    for columna in columnas_edad:
        if columna in df.columns:
            # Normalizar edad y columnas de agrupación a string/minúsculas ANTES de filtrar
            df[columna] = df[columna].astype(str).str.strip().str.lower()
            for col in columnas_agrupacion:
                df[col] = df[col].astype(str)

            # Creando la máscara para filtrar
            mask_mas = df[columna].isin(categorias_mas_25)
            mask_menos = df[columna].isin(categorias_menos_25)

            # Agrupando los datos filtrados y sumamos el 'Total'
            df_mas = df[mask_mas].groupby(columnas_agrupacion, as_index=False, observed=True)['Total'].sum(min_count=0)
            df_menos = df[mask_menos].groupby(columnas_agrupacion, as_index=False, observed=True)['Total'].sum(min_count=0)

            # Creando la columna 'edad' con el nombre unificado
            df_mas[columna] = '25_o_mas'
            df_menos[columna] = 'menos_de_25'

            # Eliminando las categorías no agrupadas
            df = df[~(mask_mas | mask_menos)]

            # Unimos la nueva categoría al dataset original del que provenían los datos
            partes = [d for d in [df, df_mas, df_menos] if len(d) > 0]
            df = pd.concat(partes, ignore_index=True)
            df[columna] = df[columna].astype(str).str.lower()
            df[columna] = df[columna].astype('category')

            for col in columnas_agrupacion:
                df[col] = df[col].astype('category')

            # Actualizamos la lista
            dataframes[i] = df

# Desempaquetamos fuera del bucle para no perder las referencias
df_76_95, df_96_01, df_02_25 = dataframes

In [58]:
for i, df in enumerate(dataframes):
    for columna in columnas_edad:
        if columna in df.columns:
            print()
            print(f'Valores únicos para edad en {df.attrs['nombre']}')
            print(df[columna].unique())

Valores únicos para edad en df_76_95
['total', '25_o_mas', 'menos_de_25']
Categories (3, object): ['25_o_mas', 'menos_de_25', 'total']

Valores únicos para edad en df_96_01
['total', '25_o_mas', 'menos_de_25']
Categories (3, object): ['25_o_mas', 'menos_de_25', 'total']

Valores únicos para edad en df_02_25
['total', '25_o_mas', 'menos_de_25']
Categories (3, object): ['25_o_mas', 'menos_de_25', 'total']

In [59]:
print(df['Edad'].unique())

['total', '25_o_mas', 'menos_de_25']
Categories (3, object): ['25_o_mas', 'menos_de_25', 'total']

### Transformación de los datos de "Periodo"

In [60]:
trimestres_map = {
    'I': '1',
    'II': '2',
    'III': '3',
    'IV': '4',
    '1': '1', '2': '2', '3': '3', '4': '4'
}

# Conversión de "Periodo" a string y a formato internacional para manejarlo mejor
for i, df in enumerate(dataframes):
    df['Periodo'] = df['Periodo'].astype('string')

    # Separación de la información en diferentes columnas para su posterior uso
    df['año'] = df['Periodo'].str[:4]
    df['trimestre'] = df['Periodo'].str[5:].map(trimestres_map)

    texto_fecha = df['año'].astype('string') + "Q" + df['trimestre'].astype('string')
    df['Periodo'] = texto_fecha.astype('category')
    df['fecha'] = pd.PeriodIndex(texto_fecha, freq="Q").to_timestamp()

    df['año'] = df['año'].astype(int)
    df['trimestre'] = df['trimestre'].astype(int)

    df = df.set_index('fecha').sort_index()
    df = df.reset_index()
    dataframes[i] = df

    print(f'Información acerca de {df.attrs['nombre']}')
    print(df.info())

df_76_95, df_96_01, df_02_25 = dataframes

Información acerca de df_76_95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4212 entries, 0 to 4211
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                4212 non-null   datetime64[ns]
 1   Sexo                                 4212 non-null   category
 2   Grupos de edad (4)                   4212 non-null   category
 3   Relación con la actividad económica  4212 non-null   category
 4   Periodo                              4212 non-null   category
 5   Total                                4212 non-null   float64
 6   año                                  4212 non-null   int64
 7   trimestre                            4212 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(1), int64(2)
memory usage: 151.3 KB
None
Información acerca de df_96_01
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                1296 non-null   datetime64[ns]
 1   Sexo                                 1296 non-null   category
 2   Grupos de edad (4)                   1296 non-null   category
 3   Relación con la actividad económica  1296 non-null   category
 4   Periodo                              1296 non-null   category
 5   Total                                1296 non-null   float64
 6   año                                  1296 non-null   int64
 7   trimestre                            1296 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(1), int64(2)
memory usage: 46.9 KB
None
Información acerca de df_02_25
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5184 entries, 0 to 5183
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   fecha                                5184 non-null   datetime64[ns]
 1   Sexo                                 5184 non-null   category
 2   Edad                                 5184 non-null   category
 3   Relación con la actividad económica  5184 non-null   category
 4   Periodo                              5184 non-null   category
 5   Total                                5184 non-null   float64
 6   año                                  5184 non-null   int64
 7   trimestre                            5184 non-null   int64
dtypes: category(4), datetime64[ns](1), float64(1), int64(2)
memory usage: 185.7 KB
None

### Cambios de nombre a columnas

In [61]:
df_76_95 = df_76_95.rename(columns={
    'Sexo': 'sexo',
    'Grupos de edad (4)': 'edad',
    'Relación con la actividad económica': 'relacion_actividad_economica',
    'Periodo': 'periodo',
    'Total': 'valor'
})

df_96_01 = df_96_01.rename(columns={
    'Sexo': 'sexo',
    'Grupos de edad (4)': 'edad',
    'Relación con la actividad económica': 'relacion_actividad_economica',
    'Periodo': 'periodo',
    'Total': 'valor'
})

df_02_25 = df_02_25.rename(columns={
    'Sexo': 'sexo',
    'Edad': 'edad',
    'Relación con la actividad económica': 'relacion_actividad_economica',
    'Periodo': 'periodo',
    'Total': 'valor'
})

# 3. Unión en un único dataset

In [62]:
df_final= pd.concat([df_76_95, df_96_01, df_02_25], ignore_index=True)
# Eliminar duplicados de ruptura metodológica 2002, conservar serie más moderna
cols_clave = [c for c in df_final.columns if c not in ['Total', 'total', 'valor', 'Value']]
n_antes = len(df_final)
df_final = df_final.drop_duplicates(subset=cols_clave, keep='last').reset_index(drop=True)
print(f'Filas: {n_antes} → {len(df_final)} ({n_antes - len(df_final)} duplicados eliminados)')

sexo_map = {
    'Ambos sexos': 'ambos_sexos',
    'Varones': 'hombres',
    'Hombres': 'hombres',
    'hombres': 'hombres',
    'Mujeres': 'mujeres',
    'mujeres': 'mujeres'
}

relacion_actividad_economica_map = {
    'Población de 16 y más años': 'poblacion_mayor_16',
    'Activos': 'activos',
    'Ocupados': 'ocupados',
    'Parados': 'parados',
    'Parados que buscan primer empleo': 'parados_1er_empleo',
    'Inactivos': 'inactivos',
    'Total': 'poblacion_mayor_16'
}


df_final['relacion_actividad_economica'] = df_final['relacion_actividad_economica'].map(relacion_actividad_economica_map)

df_final['sexo'] = df_final['sexo'].map(sexo_map)

columnas_texto = df_final.select_dtypes(include=['category']).columns

for columna in columnas_texto:
    df_final[columna] = df_final[columna].str.lower()

df_final = df_final.sort_values('fecha').reset_index(drop=True)

df_final

Filas: 10692 → 10692 (0 duplicados eliminados)

,fecha,sexo,edad,relacion_actividad_economica,periodo,valor,año,trimestre
0,1976-07-01,mujeres,menos_de_25,poblacion_mayor_16,1976Q3,2448.9,1976,3
1,1976-07-01,ambos_sexos,total,activos,1976Q3,13366.3,1976,3
2,1976-07-01,hombres,menos_de_25,ocupados,1976Q3,1437.7,1976,3
3,1976-07-01,mujeres,25_o_mas,poblacion_mayor_16,1976Q3,10782.6,1976,3
4,1976-07-01,ambos_sexos,menos_de_25,parados,1976Q3,280.0,1976,3
...,...,...,...,...,...,...,...,...
10687,2025-10-01,ambos_sexos,total,parados_1er_empleo,2025Q4,236.4,2025,4
10688,2025-10-01,ambos_sexos,total,parados,2025Q4,2477.1,2025,4
10689,2025-10-01,ambos_sexos,total,ocupados,2025Q4,22463.3,2025,4
10690,2025-10-01,mujeres,total,ocupados,2025Q4,10457.5,2025,4
10691,2025-10-01,mujeres,menos_de_25,poblacion_mayor_16,2025Q4,2355.5,2025,4

## Pivotando La tabla para poder analizarla y tener solo un registro por día

In [63]:
df_final = df_final.pivot_table(
    index=['fecha', 'año', 'trimestre', 'periodo'],
    columns=['relacion_actividad_economica', 'sexo', 'edad'],
    values='valor'
).reset_index()


# Convirtiendo el nombre de las columnas en snake_case
df_final.columns = ['_'.join(columna).strip('_') if isinstance(columna, tuple) else columna for columna in df_final.columns.values]
df_final.columns = [columna.lower().replace(' ', '_') for columna in df_final.columns]

df_final = df_final.sort_values('fecha').reset_index(drop=True)
df_final

,fecha,año,trimestre,periodo,activos_ambos_sexos_25_o_mas,activos_ambos_sexos_menos_de_25,activos_ambos_sexos_total,activos_hombres_25_o_mas,activos_hombres_menos_de_25,activos_hombres_total,...,parados_1er_empleo_mujeres_total,poblacion_mayor_16_ambos_sexos_25_o_mas,poblacion_mayor_16_ambos_sexos_menos_de_25,poblacion_mayor_16_ambos_sexos_total,poblacion_mayor_16_hombres_25_o_mas,poblacion_mayor_16_hombres_menos_de_25,poblacion_mayor_16_hombres_total,poblacion_mayor_16_mujeres_25_o_mas,poblacion_mayor_16_mujeres_menos_de_25,poblacion_mayor_16_mujeres_total
0,1976-07-01,1976,3,1976Q3,10527.5,2838.7,13366.3,7967.2,1588.8,9555.9,...,106.2,20534.0,4945.2,25479.2,9751.4,2496.3,12247.7,10782.6,2448.9,13231.5
1,1976-10-01,1976,4,1976Q4,10463.3,2833.4,13296.7,7940.1,1576.6,9516.8,...,111.9,20554.6,4963.0,25517.7,9763.0,2505.4,12268.4,10791.7,2457.7,13249.4
2,1977-01-01,1977,1,1977Q1,10448.6,2821.0,13269.7,7935.3,1569.8,9505.1,...,103.5,20609.0,4987.5,25596.5,9790.8,2517.8,12308.5,10818.2,2469.7,13288.0
3,1977-04-01,1977,2,1977Q2,10436.7,2775.0,13211.7,7964.2,1543.7,9507.8,...,103.5,20677.5,5014.5,25691.9,9825.8,2531.4,12357.1,10851.7,2483.1,13334.8
4,1977-07-01,1977,3,1977Q3,10457.1,2843.8,13300.9,7975.3,1576.6,9551.9,...,134.1,20733.2,5038.1,25771.3,9854.6,2543.3,12397.9,10878.6,2494.9,13373.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,2024-10-01,2024,4,2024Q4,22708.9,1744.4,24453.3,11978.7,960.7,12939.5,...,133.8,37001.7,4808.4,41810.1,17855.3,2467.1,20322.5,19146.4,2341.2,21487.6
194,2025-01-01,2025,1,2025Q1,22854.4,1700.1,24554.5,11981.3,941.4,12922.6,...,139.5,37095.4,4826.0,41921.3,17909.0,2487.4,20396.5,19186.2,2338.5,21524.9
195,2025-04-01,2025,2,2025Q2,22985.6,1836.3,24821.8,12084.7,996.7,13081.4,...,145.8,37196.1,4852.4,42048.5,17961.8,2500.6,20462.5,19234.3,2351.7,21586.0
196,2025-07-01,2025,3,2025Q3,23016.6,1983.7,25000.3,12103.9,1061.9,13165.9,...,174.7,37321.5,4839.9,42161.5,18025.4,2505.1,20530.4,19296.3,2334.9,21631.1
197,2025-10-01,2025,4,2025Q4,23167.9,1772.5,24940.4,12196.0,962.9,13159.1,...,132.4,37448.6,4866.6,42315.3,18101.6,2511.1,20612.7,19347.1,2355.5,21702.5

In [64]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 58 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   fecha                                       198 non-null    datetime64[ns]
 1   año                                         198 non-null    int64
 2   trimestre                                   198 non-null    int64
 3   periodo                                     198 non-null    string
 4   activos_ambos_sexos_25_o_mas                198 non-null    float64
 5   activos_ambos_sexos_menos_de_25             198 non-null    float64
 6   activos_ambos_sexos_total                   198 non-null    float64
 7   activos_hombres_25_o_mas                    198 non-null    float64
 8   activos_hombres_menos_de_25                 198 non-null    float64
 9   activos_hombres_total                       198 non-null    float64
 10  activos_mujeres_25_o_mas                    198 non-null    float64
 11  activos_mujeres_menos_de_25                 198 non-null    float64
 12  activos_mujeres_total                       198 non-null    float64
 13  inactivos_ambos_sexos_25_o_mas              198 non-null    float64
 14  inactivos_ambos_sexos_menos_de_25           198 non-null    float64
 15  inactivos_ambos_sexos_total                 198 non-null    float64
 16  inactivos_hombres_25_o_mas                  198 non-null    float64
 17  inactivos_hombres_menos_de_25               198 non-null    float64
 18  inactivos_hombres_total                     198 non-null    float64
 19  inactivos_mujeres_25_o_mas                  198 non-null    float64
 20  inactivos_mujeres_menos_de_25               198 non-null    float64
 21  inactivos_mujeres_total                     198 non-null    float64
 22  ocupados_ambos_sexos_25_o_mas               198 non-null    float64
 23  ocupados_ambos_sexos_menos_de_25            198 non-null    float64
 24  ocupados_ambos_sexos_total                  198 non-null    float64
 25  ocupados_hombres_25_o_mas                   198 non-null    float64
 26  ocupados_hombres_menos_de_25                198 non-null    float64
 27  ocupados_hombres_total                      198 non-null    float64
 28  ocupados_mujeres_25_o_mas                   198 non-null    float64
 29  ocupados_mujeres_menos_de_25                198 non-null    float64
 30  ocupados_mujeres_total                      198 non-null    float64
 31  parados_ambos_sexos_25_o_mas                198 non-null    float64
 32  parados_ambos_sexos_menos_de_25             198 non-null    float64
 33  parados_ambos_sexos_total                   198 non-null    float64
 34  parados_hombres_25_o_mas                    198 non-null    float64
 35  parados_hombres_menos_de_25                 198 non-null    float64
 36  parados_hombres_total                       198 non-null    float64
 37  parados_mujeres_25_o_mas                    198 non-null    float64
 38  parados_mujeres_menos_de_25                 198 non-null    float64
 39  parados_mujeres_total                       198 non-null    float64
 40  parados_1er_empleo_ambos_sexos_25_o_mas     198 non-null    float64
 41  parados_1er_empleo_ambos_sexos_menos_de_25  198 non-null    float64
 42  parados_1er_empleo_ambos_sexos_total        198 non-null    float64
 43  parados_1er_empleo_hombres_25_o_mas         198 non-null    float64
 44  parados_1er_empleo_hombres_menos_de_25      198 non-null    float64
 45  parados_1er_empleo_hombres_total            198 non-null    float64
 46  parados_1er_empleo_mujeres_25_o_mas         198 non-null    float64
 47  parados_1er_empleo_mujeres_menos_de_25      198 non-null    float64
 48  parados_1er_empleo_mujeres_total            198 non-null    float64
 49  poblacion_mayor_16_ambos_sexos_25_o_mas     198 non-null    float64
 50  poblacion_mayor_16_ambos_sexos_menos_de_25  198 non-null    float64
 51  poblacion_mayor_16_ambos_sexos_total        198 non-null    float64
 52  poblacion_mayor_16_hombres_25_o_mas         198 non-null    float64
 53  poblacion_mayor_16_hombres_menos_de_25      198 non-null    float64
 54  poblacion_mayor_16_hombres_total            198 non-null    float64
 55  poblacion_mayor_16_mujeres_25_o_mas         198 non-null    float64
 56  poblacion_mayor_16_mujeres_menos_de_25      198 non-null    float64
 57  poblacion_mayor_16_mujeres_total            198 non-null    float64
dtypes: datetime64[ns](1), float64(54), int64(2), string(1)
memory usage: 89.8 KB

# 4. Ajustando los datos anteriores a 2002 con la serie retropolada de parados
Para ello, se va a utilizar el dataset ya preprocesado de parados. La diferencia entre la metodología antigua y la moderna pasará a inactivos. El cambio de metodología endureció las condiciones bajo las que se puede considerar a a una persona desempleada al considerar nuevos parámetros de búsqueda activa. En la nueva metodología todos esos parados que ahora no pasan el corte ahora son clasificados como inactivos.

In [65]:
from pathlib import Path
ruta_parados = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets') / 'parados_sexo_edad.csv'
df_paro = pd.read_csv(ruta_parados)
df_paro.head()

,fecha,año,trimestre,periodo,parados_ambos_sexos_total,diferencia_parados_ambos_sexos_total,parados_ambos_sexos_menos_de_25,diferencia_parados_ambos_sexos_menos_de_25,parados_ambos_sexos_25_o_mas,diferencia_parados_ambos_sexos_25_o_mas,...,tasa_paro_hombres_menos_de_25,tasa_paro_mujeres_total,tasa_paro_mujeres_25_o_mas,tasa_paro_mujeres_menos_de_25,brecha_genero_paro,tasa_paro_juvenil_ratio,ratio_paro_juvenil,brecha_genero_parados,ratio_feminizacion_paro,indice_relativo_paro
0,1976-07-01,1976,3,1976Q3,589.000000,0.000000,280.000000,0.000000,309.000000,0.000000,...,9.510322,4.779151,2.077800,10.319174,0.521093,3.360424,47.538200,-224.800000,30.916808,20.217853
1,1976-10-01,1976,4,1976Q4,627.771632,-0.228368,303.871632,-0.128368,323.900000,0.000000,...,10.584462,4.936639,1.969677,10.900700,0.300381,3.464619,48.404805,-254.614792,29.724185,21.548717
2,1977-01-01,1977,1,1977Q1,652.867832,-1.232168,313.474892,-0.625108,339.392940,-0.507060,...,11.132531,5.014477,1.989001,11.093115,0.131274,3.421728,48.015062,-275.341612,28.912913,22.410162
3,1977-04-01,1977,2,1977Q2,629.136744,-2.263256,307.356591,-0.943409,321.780153,-1.319847,...,11.048858,4.970753,1.909478,11.118311,0.288939,3.593123,48.853702,-260.974861,29.259290,21.595575
4,1977-07-01,1977,3,1977Q3,707.184698,-3.715302,373.656013,-1.943987,333.528686,-1.871314,...,12.866877,5.971277,2.131255,13.498627,0.909274,4.121576,52.837118,-259.628132,31.643541,24.274628

In [66]:
# CHECKS DE CONSISTENCIA
# ocupados + parados = activos
# activos + inactivos = población_mayor_16

categorias = [
    'ambos_sexos_total', 'ambos_sexos_25_o_mas', 'ambos_sexos_menos_de_25',
    'hombres_total', 'hombres_25_o_mas', 'hombres_menos_de_25',
    'mujeres_total', 'mujeres_25_o_mas', 'mujeres_menos_de_25',
]

print('=== CHECK 1: ocupados + parados = activos ===')
for cat in categorias:
    suma = df_final[f'ocupados_{cat}'] + df_final[f'parados_{cat}']
    diff = (suma - df_final[f'activos_{cat}']).abs()
    print(f'  {cat}: error medio = {diff.mean():.2f} | máx = {diff.max():.2f}')

print()
print('=== CHECK 2: activos + inactivos = población_mayor_16 ===')
for cat in categorias:
    suma = df_final[f'activos_{cat}'] + df_final[f'inactivos_{cat}']
    diff = (suma - df_final[f'poblacion_mayor_16_{cat}']).abs()
    print(f'  {cat}: error medio = {diff.mean():.2f} | máx = {diff.max():.2f}')

=== CHECK 1: ocupados + parados = activos ===
  ambos_sexos_total: error medio = 0.02 | máx = 0.10
  ambos_sexos_25_o_mas: error medio = 0.09 | máx = 0.50
  ambos_sexos_menos_de_25: error medio = 0.05 | máx = 0.20
  hombres_total: error medio = 0.03 | máx = 0.10
  hombres_25_o_mas: error medio = 0.08 | máx = 0.40
  hombres_menos_de_25: error medio = 0.04 | máx = 0.20
  mujeres_total: error medio = 0.03 | máx = 0.10
  mujeres_25_o_mas: error medio = 0.08 | máx = 0.40
  mujeres_menos_de_25: error medio = 0.04 | máx = 0.20

=== CHECK 2: activos + inactivos = población_mayor_16 ===
  ambos_sexos_total: error medio = 116.65 | máx = 340.10
  ambos_sexos_25_o_mas: error medio = 6.30 | máx = 21.10
  ambos_sexos_menos_de_25: error medio = 110.43 | máx = 330.10
  hombres_total: error medio = 116.65 | máx = 340.00
  hombres_25_o_mas: error medio = 6.30 | máx = 21.10
  hombres_menos_de_25: error medio = 110.42 | máx = 330.30
  mujeres_total: error medio = 0.03 | máx = 0.10
  mujeres_25_o_mas: error medio = 0.07 | máx = 0.40
  mujeres_menos_de_25: error medio = 0.05 | máx = 0.20

In [67]:
# CHECK FINAL COMBINADO
print('=== CHECK 3: ocupados + parados + inactivos = población_mayor_16 ===')
for cat in categorias:
    suma = (df_final[f'ocupados_{cat}']
          + df_final[f'parados_{cat}']
          + df_final[f'inactivos_{cat}'])
    diff = (suma - df_final[f'poblacion_mayor_16_{cat}']).abs()
    pct = (diff / df_final[f'poblacion_mayor_16_{cat}'] * 100)
    print(f'  {cat}: error medio = {diff.mean():.2f} ({pct.mean():.3f}%) | máx = {diff.max():.2f}')

=== CHECK 3: ocupados + parados + inactivos = población_mayor_16 ===
  ambos_sexos_total: error medio = 116.65 (0.407%) | máx = 340.10
  ambos_sexos_25_o_mas: error medio = 6.30 (0.026%) | máx = 21.00
  ambos_sexos_menos_de_25: error medio = 110.43 (1.980%) | máx = 330.10
  hombres_total: error medio = 116.66 (0.841%) | máx = 340.10
  hombres_25_o_mas: error medio = 6.31 (0.054%) | máx = 21.10
  hombres_menos_de_25: error medio = 110.43 (3.900%) | máx = 330.20
  mujeres_total: error medio = 0.03 (0.000%) | máx = 0.10
  mujeres_25_o_mas: error medio = 0.10 (0.001%) | máx = 0.50
  mujeres_menos_de_25: error medio = 0.06 (0.002%) | máx = 0.20

Los chequeos de consistencia entre las propias series del ine revelan que la retropolación no fue realizada de forma perfecta. La suma total de población mayor de 16 años tiene un ligero error que será corregido recalculando la columna en base a las categorías que la componen de forma exhaustiva.

In [68]:
# 1. Reemplazar parados con valores corregidos
columnas_parados = [c for c in df_paro.columns if c.startswith('parados_') and 'diferencia' not in c]

df_final = df_final.drop(columns=columnas_parados, errors='ignore')
df_final = df_final.merge(df_paro[['periodo'] + columnas_parados], on='periodo', how='left')

print(f'{len(columnas_parados)} columnas de parados reemplazadas')

# 2. Recalcular activos e inactivos por identidad contable
categorias = [
    'ambos_sexos_total', 'ambos_sexos_25_o_mas', 'ambos_sexos_menos_de_25',
    'hombres_total', 'hombres_25_o_mas', 'hombres_menos_de_25',
    'mujeres_total', 'mujeres_25_o_mas', 'mujeres_menos_de_25',
]

for cat in categorias:
    df_final[f'activos_{cat}'] = df_final[f'ocupados_{cat}'] + df_final[f'parados_{cat}']
    df_final[f'inactivos_{cat}'] = df_final[f'poblacion_mayor_16_{cat}'] - df_final[f'activos_{cat}']

print(f'{len(categorias)} categorías de activos e inactivos recalculadas por identidad contable')

9 columnas de parados reemplazadas
9 categorías de activos e inactivos recalculadas por identidad contable

In [69]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 58 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   fecha                                       198 non-null    datetime64[ns]
 1   año                                         198 non-null    int64
 2   trimestre                                   198 non-null    int64
 3   periodo                                     198 non-null    object
 4   activos_ambos_sexos_25_o_mas                198 non-null    float64
 5   activos_ambos_sexos_menos_de_25             198 non-null    float64
 6   activos_ambos_sexos_total                   198 non-null    float64
 7   activos_hombres_25_o_mas                    198 non-null    float64
 8   activos_hombres_menos_de_25                 198 non-null    float64
 9   activos_hombres_total                       198 non-null    float64
 10  activos_mujeres_25_o_mas                    198 non-null    float64
 11  activos_mujeres_menos_de_25                 198 non-null    float64
 12  activos_mujeres_total                       198 non-null    float64
 13  inactivos_ambos_sexos_25_o_mas              198 non-null    float64
 14  inactivos_ambos_sexos_menos_de_25           198 non-null    float64
 15  inactivos_ambos_sexos_total                 198 non-null    float64
 16  inactivos_hombres_25_o_mas                  198 non-null    float64
 17  inactivos_hombres_menos_de_25               198 non-null    float64
 18  inactivos_hombres_total                     198 non-null    float64
 19  inactivos_mujeres_25_o_mas                  198 non-null    float64
 20  inactivos_mujeres_menos_de_25               198 non-null    float64
 21  inactivos_mujeres_total                     198 non-null    float64
 22  ocupados_ambos_sexos_25_o_mas               198 non-null    float64
 23  ocupados_ambos_sexos_menos_de_25            198 non-null    float64
 24  ocupados_ambos_sexos_total                  198 non-null    float64
 25  ocupados_hombres_25_o_mas                   198 non-null    float64
 26  ocupados_hombres_menos_de_25                198 non-null    float64
 27  ocupados_hombres_total                      198 non-null    float64
 28  ocupados_mujeres_25_o_mas                   198 non-null    float64
 29  ocupados_mujeres_menos_de_25                198 non-null    float64
 30  ocupados_mujeres_total                      198 non-null    float64
 31  parados_1er_empleo_ambos_sexos_25_o_mas     198 non-null    float64
 32  parados_1er_empleo_ambos_sexos_menos_de_25  198 non-null    float64
 33  parados_1er_empleo_ambos_sexos_total        198 non-null    float64
 34  parados_1er_empleo_hombres_25_o_mas         198 non-null    float64
 35  parados_1er_empleo_hombres_menos_de_25      198 non-null    float64
 36  parados_1er_empleo_hombres_total            198 non-null    float64
 37  parados_1er_empleo_mujeres_25_o_mas         198 non-null    float64
 38  parados_1er_empleo_mujeres_menos_de_25      198 non-null    float64
 39  parados_1er_empleo_mujeres_total            198 non-null    float64
 40  poblacion_mayor_16_ambos_sexos_25_o_mas     198 non-null    float64
 41  poblacion_mayor_16_ambos_sexos_menos_de_25  198 non-null    float64
 42  poblacion_mayor_16_ambos_sexos_total        198 non-null    float64
 43  poblacion_mayor_16_hombres_25_o_mas         198 non-null    float64
 44  poblacion_mayor_16_hombres_menos_de_25      198 non-null    float64
 45  poblacion_mayor_16_hombres_total            198 non-null    float64
 46  poblacion_mayor_16_mujeres_25_o_mas         198 non-null    float64
 47  poblacion_mayor_16_mujeres_menos_de_25      198 non-null    float64
 48  poblacion_mayor_16_mujeres_total            198 non-null    float64
 49  parados_ambos_sexos_total                   198 non-null    float64
 50  parados_ambos_sexos_menos_de_25             198 non-null    float64
 51  parados_ambos_sexos_25_o_mas                198 non-null    float64
 52  parados_hombres_total                       198 non-null    float64
 53  parados_hombres_menos_de_25                 198 non-null    float64
 54  parados_hombres_25_o_mas                    198 non-null    float64
 55  parados_mujeres_total                       198 non-null    float64
 56  parados_mujeres_menos_de_25                 198 non-null    float64
 57  parados_mujeres_25_o_mas                    198 non-null    float64
dtypes: datetime64[ns](1), float64(54), int64(2), object(1)
memory usage: 89.8+ KB

In [70]:
# CHECKS DE CONSISTENCIA
# ocupados + parados = activos
# activos + inactivos = población_mayor_16

categorias = [
    'ambos_sexos_total', 'ambos_sexos_25_o_mas', 'ambos_sexos_menos_de_25',
    'hombres_total', 'hombres_25_o_mas', 'hombres_menos_de_25',
    'mujeres_total', 'mujeres_25_o_mas', 'mujeres_menos_de_25',
]

print('=== CHECK 1: ocupados + parados = activos ===')
for cat in categorias:
    suma = df_final[f'ocupados_{cat}'] + df_final[f'parados_{cat}']
    diff = (suma - df_final[f'activos_{cat}']).abs()
    print(f'  {cat}: error medio = {diff.mean():.4f} | máx = {diff.max():.4f}')

print()
print('=== CHECK 2: activos + inactivos = población_mayor_16 ===')
for cat in categorias:
    suma = df_final[f'activos_{cat}'] + df_final[f'inactivos_{cat}']
    diff = (suma - df_final[f'poblacion_mayor_16_{cat}']).abs()
    print(f'  {cat}: error medio = {diff.mean():.2f} | máx = {diff.max():.2f}')

=== CHECK 1: ocupados + parados = activos ===
  ambos_sexos_total: error medio = 0.0000 | máx = 0.0000
  ambos_sexos_25_o_mas: error medio = 0.0000 | máx = 0.0000
  ambos_sexos_menos_de_25: error medio = 0.0000 | máx = 0.0000
  hombres_total: error medio = 0.0000 | máx = 0.0000
  hombres_25_o_mas: error medio = 0.0000 | máx = 0.0000
  hombres_menos_de_25: error medio = 0.0000 | máx = 0.0000
  mujeres_total: error medio = 0.0000 | máx = 0.0000
  mujeres_25_o_mas: error medio = 0.0000 | máx = 0.0000
  mujeres_menos_de_25: error medio = 0.0000 | máx = 0.0000

=== CHECK 2: activos + inactivos = población_mayor_16 ===
  ambos_sexos_total: error medio = 0.00 | máx = 0.00
  ambos_sexos_25_o_mas: error medio = 0.00 | máx = 0.00
  ambos_sexos_menos_de_25: error medio = 0.00 | máx = 0.00
  hombres_total: error medio = 0.00 | máx = 0.00
  hombres_25_o_mas: error medio = 0.00 | máx = 0.00
  hombres_menos_de_25: error medio = 0.00 | máx = 0.00
  mujeres_total: error medio = 0.00 | máx = 0.00
  mujeres_25_o_mas: error medio = 0.00 | máx = 0.00
  mujeres_menos_de_25: error medio = 0.00 | máx = 0.00

In [71]:
# CHECK FINAL COMBINADO
print('=== CHECK 3: ocupados + parados + inactivos = población_mayor_16 ===')
for cat in categorias:
    suma = (df_final[f'ocupados_{cat}']
          + df_final[f'parados_{cat}']
          + df_final[f'inactivos_{cat}'])
    diff = (suma - df_final[f'poblacion_mayor_16_{cat}']).abs()
    pct = (diff / df_final[f'poblacion_mayor_16_{cat}'] * 100)
    print(f'  {cat}: error medio = {diff.mean():.2f} ({pct.mean():.3f}%) | máx = {diff.max():.2f}')

=== CHECK 3: ocupados + parados + inactivos = población_mayor_16 ===
  ambos_sexos_total: error medio = 0.00 (0.000%) | máx = 0.00
  ambos_sexos_25_o_mas: error medio = 0.00 (0.000%) | máx = 0.00
  ambos_sexos_menos_de_25: error medio = 0.00 (0.000%) | máx = 0.00
  hombres_total: error medio = 0.00 (0.000%) | máx = 0.00
  hombres_25_o_mas: error medio = 0.00 (0.000%) | máx = 0.00
  hombres_menos_de_25: error medio = 0.00 (0.000%) | máx = 0.00
  mujeres_total: error medio = 0.00 (0.000%) | máx = 0.00
  mujeres_25_o_mas: error medio = 0.00 (0.000%) | máx = 0.00
  mujeres_menos_de_25: error medio = 0.00 (0.000%) | máx = 0.00

In [72]:
print('Rango de fechas el dataset:', df_final['fecha'].min(), '-', df_final['fecha'].max())
print()
print('Estadísticas básicas:')
print(df_final.describe().round(2))

Rango de fechas el dataset: 1976-07-01 00:00:00 - 2025-10-01 00:00:00

Estadísticas básicas:
                               fecha      año  trimestre  \
count                            198   198.00     198.00
mean   2001-02-14 12:07:16.363636352  2000.75       2.51
min              1976-07-01 00:00:00  1976.00       1.00
25%              1988-10-24 00:00:00  1988.25       2.00
50%              2001-02-15 00:00:00  2001.00       3.00
75%              2013-06-08 06:00:00  2013.00       3.75
max              2025-10-01 00:00:00  2025.00       4.00
std                              NaN    14.33       1.12

       activos_ambos_sexos_25_o_mas  activos_ambos_sexos_menos_de_25  \
count                        198.00                           198.00
mean                       16361.97                          2348.35
min                        10435.28                          1288.20
25%                        11901.21                          1805.80
50%                        15477.40                          2451.82
75%                        21314.65                          2834.33
max                        23168.20                          3151.97
std                         4575.88                           524.14

       activos_ambos_sexos_total  activos_hombres_25_o_mas  \
count                     198.00                    198.00
mean                    18710.31                   9853.14
min                     13209.44                   7934.80
25%                     14976.53                   8257.60
50%                     17880.79                   9520.75
75%                     22967.65                  11500.52
max                     25000.30                  12196.00
std                      4111.50                   1599.82

       activos_hombres_menos_de_25  activos_hombres_total  \
count                       198.00                 198.00
mean                       1297.39               11150.54
min                         722.50                9497.02
25%                         966.55                9845.43
50%                        1379.25               10885.95
75%                        1577.28               12416.80
max                        1697.60               13199.40
std                         301.11                1351.99

       activos_mujeres_25_o_mas  ...  poblacion_mayor_16_mujeres_total  \
count                    198.00  ...                            198.00
mean                    6508.83  ...                          17506.15
min                     2472.21  ...                          13231.50
25%                     3649.59  ...                          15454.00
50%                     5956.65  ...                          17432.60
75%                     9833.50  ...                          19763.42
max                    10971.80  ...                          21702.50
std                     2994.07  ...                           2462.08

       parados_ambos_sexos_total  parados_ambos_sexos_menos_de_25  \
count                     198.00                           198.00
mean                     2913.27                           770.35
min                       589.00                           280.00
25%                      2202.41                           525.05
50%                      2757.25                           766.95
75%                      3357.44                           966.18
max                      6278.20                          1355.03
std                      1210.59                           277.54

       parados_ambos_sexos_25_o_mas  parados_hombres_total  \
count                        198.00                 198.00
mean                        2142.92                1501.97
min                          309.00                 406.90
25%                         1431.06                1012.52
50%                         1741.20                1403.80
75%                         2727.75                1734.67
max                         5297.60                3358.40
std                         1165.06                 644.95

       parados_hombres_menos_de_25  parados_hombres_25_o_mas  \
count                       198.00                    198.00
mean                        393.11                   1108.85
min                         151.10                    255.80
25%                         265.15                    707.58
50%                         376.48                    991.17
75%                         494.62                   1268.85
max                         739.08                   2815.60
std                         147.22                    582.66

       parados_mujeres_total  parados_mujeres_menos_de_25  \
count                 198.00                       198.00
mean                 1411.30                       377.24
min                   182.10                       129.00
25%                  1053.25                       254.75
50%                  1311.26                       358.10
75%                  1706.89                       496.81
max                  2919.90                       672.91
std                   611.44                       138.72

       parados_mujeres_25_o_mas
count                    198.00
mean                    1034.07
min                       47.21
25%                      674.27
50%                      961.10
75%                     1460.15
max                     2481.90
std                      618.50

[8 rows x 57 columns]

In [73]:
px.line(df_final, x='fecha', y = ['poblacion_mayor_16_ambos_sexos_total', 'parados_ambos_sexos_total', 'ocupados_ambos_sexos_total', 'activos_ambos_sexos_total', 'inactivos_ambos_sexos_total']).update_yaxes(range=[0, 45000])

# 5. Cálculo de nuevas variables

In [74]:
# Tasas estándar del mercado laboral (definiciones INE/ILO/Eurostat)
# - Tasa de actividad   = activos    / población 16+   * 100
# - Tasa de empleo      = ocupados   / población 16+   * 100
# - Tasa de paro        = parados    / activos         * 100   (denominador OIT: fuerza laboral)
# - Tasa de inactividad = inactivos  / población 16+   * 100

categorias = [
    'ambos_sexos_total', 'ambos_sexos_25_o_mas', 'ambos_sexos_menos_de_25',
    'hombres_total',     'hombres_25_o_mas',     'hombres_menos_de_25',
    'mujeres_total',     'mujeres_25_o_mas',     'mujeres_menos_de_25',
]

for cat in categorias:
    df_final[f'tasa_actividad_{cat}']   = df_final[f'activos_{cat}']   / df_final[f'poblacion_mayor_16_{cat}'] * 100
    df_final[f'tasa_empleo_{cat}']      = df_final[f'ocupados_{cat}']  / df_final[f'poblacion_mayor_16_{cat}'] * 100
    df_final[f'tasa_paro_{cat}']        = df_final[f'parados_{cat}']   / df_final[f'activos_{cat}']            * 100
    df_final[f'tasa_inactividad_{cat}'] = df_final[f'inactivos_{cat}'] / df_final[f'poblacion_mayor_16_{cat}'] * 100

# Métricas derivadas

df_final['brecha_genero_actividad'] = df_final['tasa_actividad_hombres_total'] - df_final['tasa_actividad_mujeres_total']
df_final['brecha_genero_empleo']    = df_final['tasa_empleo_hombres_total']    - df_final['tasa_empleo_mujeres_total']
df_final['brecha_genero_paro']      = df_final['tasa_paro_mujeres_total']      - df_final['tasa_paro_hombres_total']

df_final.filter(like='tasa_').describe().round(2)

,tasa_actividad_ambos_sexos_total,tasa_empleo_ambos_sexos_total,tasa_paro_ambos_sexos_total,tasa_inactividad_ambos_sexos_total,tasa_actividad_ambos_sexos_25_o_mas,tasa_empleo_ambos_sexos_25_o_mas,tasa_paro_ambos_sexos_25_o_mas,tasa_inactividad_ambos_sexos_25_o_mas,tasa_actividad_ambos_sexos_menos_de_25,tasa_empleo_ambos_sexos_menos_de_25,...,tasa_paro_mujeres_total,tasa_inactividad_mujeres_total,tasa_actividad_mujeres_25_o_mas,tasa_empleo_mujeres_25_o_mas,tasa_paro_mujeres_25_o_mas,tasa_inactividad_mujeres_25_o_mas,tasa_actividad_mujeres_menos_de_25,tasa_empleo_mujeres_menos_de_25,tasa_paro_mujeres_menos_de_25,tasa_inactividad_mujeres_menos_de_25
count,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00,...,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00,198.00
mean,54.32,45.92,15.47,45.68,55.39,48.33,12.59,44.61,46.00,30.88,...,18.89,58.23,41.03,34.59,15.06,58.97,42.08,27.05,36.09,57.92
std,4.48,4.66,5.06,4.48,5.45,4.56,4.70,5.45,6.33,7.83,...,5.96,10.24,12.65,10.32,5.75,12.65,5.29,6.56,10.46,5.29
min,48.35,38.35,4.41,39.45,48.24,41.42,2.94,37.38,30.14,17.44,...,4.78,45.29,22.54,21.00,1.91,43.29,27.20,15.98,10.32,48.86
25%,49.96,41.67,11.40,41.15,50.17,44.06,9.57,38.64,41.31,25.86,...,14.87,46.79,29.17,23.79,11.26,44.97,38.70,22.16,27.26,53.70
50%,52.76,46.51,15.48,47.24,54.02,48.45,12.34,45.98,47.26,29.75,...,18.92,59.78,40.16,34.74,15.15,59.84,42.45,25.95,37.12,57.55
75%,58.85,49.74,19.58,50.04,61.36,52.07,15.44,49.83,51.13,36.14,...,23.95,67.14,55.03,44.35,19.05,70.83,46.30,30.27,44.95,61.30
max,60.55,54.73,26.94,51.65,62.62,56.34,24.54,51.76,57.41,51.74,...,29.17,72.85,56.71,50.85,25.05,77.46,51.14,45.78,55.55,72.80

# 6. Guardando el dataset final en un archivo

In [75]:
# ── Recortar al rango de tasa de paro y guardar en Datasets ────────────
from pathlib import Path
FECHA_INICIO = '1976-07-01'
FECHA_FIN    = '2025-10-01'
ruta_datasets = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets')

df_final = df_final[(df_final['fecha'] >= FECHA_INICIO) & (df_final['fecha'] <= FECHA_FIN)].copy()
df_final.to_csv(ruta_datasets / 'poblacion_relacion_actividad_economica_sexo_edad.csv',
                index=False,
                encoding='utf-8-sig')

## 6.1 Añadir tasas de paro al CSV de parados

Las tasas de paro calculadas aquí (parados/activos×100) se persisten también
en `parados_sexo_edad.csv` para que el EDA de parados pueda analizar
directamente las tasas sin necesidad de recalcularlas.

In [76]:
# ── Añadir tasas de paro al CSV de parados ──────────────────────────────────
# Las tasas se calculan aquí porque este notebook tiene tanto parados como
# activos. Se guardan en el CSV de parados para análisis posterior.

from pathlib import Path

ruta_parados = Path(r'C:\Users\marco\PycharmProjects\TFM_Marcos\Datasets') / 'parados_sexo_edad.csv'
df_parados_csv = pd.read_csv(ruta_parados)
df_parados_csv['fecha'] = pd.to_datetime(df_parados_csv['fecha'])

# Columnas de tasa a añadir (9 tasas base + 2 derivadas)
cols_tasa = [
    'tasa_paro_ambos_sexos_total',
    'tasa_paro_ambos_sexos_25_o_mas',
    'tasa_paro_ambos_sexos_menos_de_25',
    'tasa_paro_hombres_total',
    'tasa_paro_hombres_25_o_mas',
    'tasa_paro_hombres_menos_de_25',
    'tasa_paro_mujeres_total',
    'tasa_paro_mujeres_25_o_mas',
    'tasa_paro_mujeres_menos_de_25',
    'brecha_genero_paro'
]

# Eliminar columnas de tasa si ya existen (por si se re-ejecuta)
cols_existentes = [c for c in cols_tasa if c in df_parados_csv.columns]
if cols_existentes:
    df_parados_csv = df_parados_csv.drop(columns=cols_existentes)
    print(f'Columnas de tasa previas eliminadas: {len(cols_existentes)}')

# Extraer tasas del df_final (solo fecha + columnas de tasa)
df_tasas = df_final[['fecha'] + cols_tasa].copy()

# Merge por fecha (left join: se conservan todas las fechas de parados)
df_parados_csv = df_parados_csv.merge(df_tasas, on='fecha', how='left')

# Guardar
df_parados_csv.to_csv(ruta_parados, index=False, encoding='utf-8-sig')

Columnas de tasa previas eliminadas: 10

# 7. Información acerca del dataset final

In [77]:
df_final.attrs['nombre'] = 'df_final'
print('Información acerca del dataset final:')
print(f'{df_final.shape[0]} trimestres × {df_final.shape[1]} columnas | Rango: {df_final["fecha"].min().date()} → {df_final["fecha"].max().date()}')
columnas = df_final.columns.tolist()
print(f'  Columnas: {columnas}')
nulos = df_final.isna().sum()
nulos_col = nulos[nulos > 0]
if len(nulos_col) > 0:
    print(f'ALERTA  {df_final.attrs['nombre']}: nulos en {nulos_col.to_dict()}')
else:
    print(f'CORRECTO  {df_final.attrs['nombre']}: sin valores nulos')
print()

Información acerca del dataset final:
198 trimestres × 97 columnas | Rango: 1976-07-01 → 2025-10-01
  Columnas: ['fecha', 'año', 'trimestre', 'periodo', 'activos_ambos_sexos_25_o_mas', 'activos_ambos_sexos_menos_de_25', 'activos_ambos_sexos_total', 'activos_hombres_25_o_mas', 'activos_hombres_menos_de_25', 'activos_hombres_total', 'activos_mujeres_25_o_mas', 'activos_mujeres_menos_de_25', 'activos_mujeres_total', 'inactivos_ambos_sexos_25_o_mas', 'inactivos_ambos_sexos_menos_de_25', 'inactivos_ambos_sexos_total', 'inactivos_hombres_25_o_mas', 'inactivos_hombres_menos_de_25', 'inactivos_hombres_total', 'inactivos_mujeres_25_o_mas', 'inactivos_mujeres_menos_de_25', 'inactivos_mujeres_total', 'ocupados_ambos_sexos_25_o_mas', 'ocupados_ambos_sexos_menos_de_25', 'ocupados_ambos_sexos_total', 'ocupados_hombres_25_o_mas', 'ocupados_hombres_menos_de_25', 'ocupados_hombres_total', 'ocupados_mujeres_25_o_mas', 'ocupados_mujeres_menos_de_25', 'ocupados_mujeres_total', 'parados_1er_empleo_ambos_sexos_25_o_mas', 'parados_1er_empleo_ambos_sexos_menos_de_25', 'parados_1er_empleo_ambos_sexos_total', 'parados_1er_empleo_hombres_25_o_mas', 'parados_1er_empleo_hombres_menos_de_25', 'parados_1er_empleo_hombres_total', 'parados_1er_empleo_mujeres_25_o_mas', 'parados_1er_empleo_mujeres_menos_de_25', 'parados_1er_empleo_mujeres_total', 'poblacion_mayor_16_ambos_sexos_25_o_mas', 'poblacion_mayor_16_ambos_sexos_menos_de_25', 'poblacion_mayor_16_ambos_sexos_total', 'poblacion_mayor_16_hombres_25_o_mas', 'poblacion_mayor_16_hombres_menos_de_25', 'poblacion_mayor_16_hombres_total', 'poblacion_mayor_16_mujeres_25_o_mas', 'poblacion_mayor_16_mujeres_menos_de_25', 'poblacion_mayor_16_mujeres_total', 'parados_ambos_sexos_total', 'parados_ambos_sexos_menos_de_25', 'parados_ambos_sexos_25_o_mas', 'parados_hombres_total', 'parados_hombres_menos_de_25', 'parados_hombres_25_o_mas', 'parados_mujeres_total', 'parados_mujeres_menos_de_25', 'parados_mujeres_25_o_mas', 'tasa_actividad_ambos_sexos_total', 'tasa_empleo_ambos_sexos_total', 'tasa_paro_ambos_sexos_total', 'tasa_inactividad_ambos_sexos_total', 'tasa_actividad_ambos_sexos_25_o_mas', 'tasa_empleo_ambos_sexos_25_o_mas', 'tasa_paro_ambos_sexos_25_o_mas', 'tasa_inactividad_ambos_sexos_25_o_mas', 'tasa_actividad_ambos_sexos_menos_de_25', 'tasa_empleo_ambos_sexos_menos_de_25', 'tasa_paro_ambos_sexos_menos_de_25', 'tasa_inactividad_ambos_sexos_menos_de_25', 'tasa_actividad_hombres_total', 'tasa_empleo_hombres_total', 'tasa_paro_hombres_total', 'tasa_inactividad_hombres_total', 'tasa_actividad_hombres_25_o_mas', 'tasa_empleo_hombres_25_o_mas', 'tasa_paro_hombres_25_o_mas', 'tasa_inactividad_hombres_25_o_mas', 'tasa_actividad_hombres_menos_de_25', 'tasa_empleo_hombres_menos_de_25', 'tasa_paro_hombres_menos_de_25', 'tasa_inactividad_hombres_menos_de_25', 'tasa_actividad_mujeres_total', 'tasa_empleo_mujeres_total', 'tasa_paro_mujeres_total', 'tasa_inactividad_mujeres_total', 'tasa_actividad_mujeres_25_o_mas', 'tasa_empleo_mujeres_25_o_mas', 'tasa_paro_mujeres_25_o_mas', 'tasa_inactividad_mujeres_25_o_mas', 'tasa_actividad_mujeres_menos_de_25', 'tasa_empleo_mujeres_menos_de_25', 'tasa_paro_mujeres_menos_de_25', 'tasa_inactividad_mujeres_menos_de_25', 'brecha_genero_actividad', 'brecha_genero_empleo', 'brecha_genero_paro']
CORRECTO  df_final: sin valores nulos

In [78]:
df_final.describe()

,fecha,año,trimestre,activos_ambos_sexos_25_o_mas,activos_ambos_sexos_menos_de_25,activos_ambos_sexos_total,activos_hombres_25_o_mas,activos_hombres_menos_de_25,activos_hombres_total,activos_mujeres_25_o_mas,...,tasa_empleo_mujeres_25_o_mas,tasa_paro_mujeres_25_o_mas,tasa_inactividad_mujeres_25_o_mas,tasa_actividad_mujeres_menos_de_25,tasa_empleo_mujeres_menos_de_25,tasa_paro_mujeres_menos_de_25,tasa_inactividad_mujeres_menos_de_25,brecha_genero_actividad,brecha_genero_empleo,brecha_genero_paro
count,198,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,...,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000
mean,2001-02-14 12:07:16.363636352,2000.747475,2.510101,16361.970915,2348.346458,18710.310806,9853.142866,1297.388687,11150.539129,6508.827251,...,34.587479,15.063705,58.966078,42.083904,27.054064,36.088973,57.916096,25.875866,24.704438,5.493171
min,1976-07-01 00:00:00,1976.000000,1.000000,10435.280153,1288.200000,13209.436744,7934.801563,722.500000,9497.016403,2472.206224,...,21.003545,1.909478,43.289692,27.202347,15.983843,10.319174,48.862758,9.317183,9.397254,-0.078338
25%,1988-10-24 00:00:00,1988.250000,2.000000,11901.209583,1805.800000,14976.526372,8257.598262,966.550000,9845.432387,3649.587157,...,23.785503,11.262480,44.967166,38.702301,22.163824,27.263077,53.704396,12.540658,11.461805,2.543953
50%,2001-02-15 00:00:00,2001.000000,3.000000,15477.400000,2451.824362,17880.793075,9520.750000,1379.250000,10885.949457,5956.650000,...,34.741909,15.152234,59.843145,42.451673,25.951280,37.123499,57.548327,25.582724,26.652294,4.149642
75%,2013-06-08 06:00:00,2013.000000,3.750000,21314.650000,2834.330665,22967.650000,11500.525000,1577.280898,12416.800000,9833.500000,...,44.349877,19.049472,70.828211,46.295604,30.268908,44.954167,61.297699,35.506228,34.694805,9.518053
max,2025-10-01 00:00:00,2025.000000,4.000000,23168.200000,3151.966515,25000.300000,12196.000000,1697.596561,13199.400000,10971.800000,...,50.849481,25.050719,77.461777,51.137242,45.779738,55.547083,72.797653,49.225624,47.279629,12.576169
std,NaN,14.327102,1.120822,4575.879743,524.135378,4111.504037,1599.817224,301.113475,1351.986728,2994.067170,...,10.318383,5.754275,12.647346,5.290364,6.556081,10.456726,5.290364,12.773999,11.602040,3.844119

In [79]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 97 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   fecha                                       198 non-null    datetime64[ns]
 1   año                                         198 non-null    int64
 2   trimestre                                   198 non-null    int64
 3   periodo                                     198 non-null    object
 4   activos_ambos_sexos_25_o_mas                198 non-null    float64
 5   activos_ambos_sexos_menos_de_25             198 non-null    float64
 6   activos_ambos_sexos_total                   198 non-null    float64
 7   activos_hombres_25_o_mas                    198 non-null    float64
 8   activos_hombres_menos_de_25                 198 non-null    float64
 9   activos_hombres_total                       198 non-null    float64
 10  activos_mujeres_25_o_mas                    198 non-null    float64
 11  activos_mujeres_menos_de_25                 198 non-null    float64
 12  activos_mujeres_total                       198 non-null    float64
 13  inactivos_ambos_sexos_25_o_mas              198 non-null    float64
 14  inactivos_ambos_sexos_menos_de_25           198 non-null    float64
 15  inactivos_ambos_sexos_total                 198 non-null    float64
 16  inactivos_hombres_25_o_mas                  198 non-null    float64
 17  inactivos_hombres_menos_de_25               198 non-null    float64
 18  inactivos_hombres_total                     198 non-null    float64
 19  inactivos_mujeres_25_o_mas                  198 non-null    float64
 20  inactivos_mujeres_menos_de_25               198 non-null    float64
 21  inactivos_mujeres_total                     198 non-null    float64
 22  ocupados_ambos_sexos_25_o_mas               198 non-null    float64
 23  ocupados_ambos_sexos_menos_de_25            198 non-null    float64
 24  ocupados_ambos_sexos_total                  198 non-null    float64
 25  ocupados_hombres_25_o_mas                   198 non-null    float64
 26  ocupados_hombres_menos_de_25                198 non-null    float64
 27  ocupados_hombres_total                      198 non-null    float64
 28  ocupados_mujeres_25_o_mas                   198 non-null    float64
 29  ocupados_mujeres_menos_de_25                198 non-null    float64
 30  ocupados_mujeres_total                      198 non-null    float64
 31  parados_1er_empleo_ambos_sexos_25_o_mas     198 non-null    float64
 32  parados_1er_empleo_ambos_sexos_menos_de_25  198 non-null    float64
 33  parados_1er_empleo_ambos_sexos_total        198 non-null    float64
 34  parados_1er_empleo_hombres_25_o_mas         198 non-null    float64
 35  parados_1er_empleo_hombres_menos_de_25      198 non-null    float64
 36  parados_1er_empleo_hombres_total            198 non-null    float64
 37  parados_1er_empleo_mujeres_25_o_mas         198 non-null    float64
 38  parados_1er_empleo_mujeres_menos_de_25      198 non-null    float64
 39  parados_1er_empleo_mujeres_total            198 non-null    float64
 40  poblacion_mayor_16_ambos_sexos_25_o_mas     198 non-null    float64
 41  poblacion_mayor_16_ambos_sexos_menos_de_25  198 non-null    float64
 42  poblacion_mayor_16_ambos_sexos_total        198 non-null    float64
 43  poblacion_mayor_16_hombres_25_o_mas         198 non-null    float64
 44  poblacion_mayor_16_hombres_menos_de_25      198 non-null    float64
 45  poblacion_mayor_16_hombres_total            198 non-null    float64
 46  poblacion_mayor_16_mujeres_25_o_mas         198 non-null    float64
 47  poblacion_mayor_16_mujeres_menos_de_25      198 non-null    float64
 48  poblacion_mayor_16_mujeres_total            198 non-null    float64
 49  parados_ambos_sexos_total                   198 non-null    float64
 50  parados_ambos_sexos_menos_de_25             198 non-null    float64
 51  parados_ambos_sexos_25_o_mas                198 non-null    float64
 52  parados_hombres_total                       198 non-null    float64
 53  parados_hombres_menos_de_25                 198 non-null    float64
 54  parados_hombres_25_o_mas                    198 non-null    float64
 55  parados_mujeres_total                       198 non-null    float64
 56  parados_mujeres_menos_de_25                 198 non-null    float64
 57  parados_mujeres_25_o_mas                    198 non-null    float64
 58  tasa_actividad_ambos_sexos_total            198 non-null    float64
 59  tasa_empleo_ambos_sexos_total               198 non-null    float64
 60  tasa_paro_ambos_sexos_total                 198 non-null    float64
 61  tasa_inactividad_ambos_sexos_total          198 non-null    float64
 62  tasa_actividad_ambos_sexos_25_o_mas         198 non-null    float64
 63  tasa_empleo_ambos_sexos_25_o_mas            198 non-null    float64
 64  tasa_paro_ambos_sexos_25_o_mas              198 non-null    float64
 65  tasa_inactividad_ambos_sexos_25_o_mas       198 non-null    float64
 66  tasa_actividad_ambos_sexos_menos_de_25      198 non-null    float64
 67  tasa_empleo_ambos_sexos_menos_de_25         198 non-null    float64
 68  tasa_paro_ambos_sexos_menos_de_25           198 non-null    float64
 69  tasa_inactividad_ambos_sexos_menos_de_25    198 non-null    float64
 70  tasa_actividad_hombres_total                198 non-null    float64
 71  tasa_empleo_hombres_total                   198 non-null    float64
 72  tasa_paro_hombres_total                     198 non-null    float64
 73  tasa_inactividad_hombres_total              198 non-null    float64
 74  tasa_actividad_hombres_25_o_mas             198 non-null    float64
 75  tasa_empleo_hombres_25_o_mas                198 non-null    float64
 76  tasa_paro_hombres_25_o_mas                  198 non-null    float64
 77  tasa_inactividad_hombres_25_o_mas           198 non-null    float64
 78  tasa_actividad_hombres_menos_de_25          198 non-null    float64
 79  tasa_empleo_hombres_menos_de_25             198 non-null    float64
 80  tasa_paro_hombres_menos_de_25               198 non-null    float64
 81  tasa_inactividad_hombres_menos_de_25        198 non-null    float64
 82  tasa_actividad_mujeres_total                198 non-null    float64
 83  tasa_empleo_mujeres_total                   198 non-null    float64
 84  tasa_paro_mujeres_total                     198 non-null    float64
 85  tasa_inactividad_mujeres_total              198 non-null    float64
 86  tasa_actividad_mujeres_25_o_mas             198 non-null    float64
 87  tasa_empleo_mujeres_25_o_mas                198 non-null    float64
 88  tasa_paro_mujeres_25_o_mas                  198 non-null    float64
 89  tasa_inactividad_mujeres_25_o_mas           198 non-null    float64
 90  tasa_actividad_mujeres_menos_de_25          198 non-null    float64
 91  tasa_empleo_mujeres_menos_de_25             198 non-null    float64
 92  tasa_paro_mujeres_menos_de_25               198 non-null    float64
 93  tasa_inactividad_mujeres_menos_de_25        198 non-null    float64
 94  brecha_genero_actividad                     198 non-null    float64
 95  brecha_genero_empleo                        198 non-null    float64
 96  brecha_genero_paro                          198 non-null    float64
dtypes: datetime64[ns](1), float64(93), int64(2), object(1)
memory usage: 150.2+ KB